---
become_override: false
ocp_username: opentlc-mgr
silent: false

num_users: "100"

# OpenShift project which contains the CyberArk DAP server and sample MySQL db
ocp4_workload_cyberark_project: "cyberlab"
