---
# Implement your workload removal tasks here
# ------------------------------------------

- name: Remove MySQL
  k8s:
    state: absent
    src: /home/{{ansible_user}}/cyberark_setup/mysql.yaml

- name: Remove CyberArk Master
  k8s:
    state: absent
    src: /home/{{ansible_user}}/cyberark_setup/master-deployment-manifest.yaml

- name: Remove CyberArk resources
  k8s:
    state: absent
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/namespace.j2
  - ./templates/service.j2
  - ./templates/dap_authn_role.j2
  - ./templates/role_binding.j2
  - ./templates/dap_cm_role.j2

- name: Remove cyberark setup files
  become: true
  file:
   state: absent
   path: "{{ item }}"
  loop:
  - /home/{{ansible_user}}/cyberark_setup

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: remove_workload tasks complete
  debug:
   msg: "CyberArk DAP Remove Workload tasks completed successfully."
  when: not silent|bool
